export default [
  {
    id: 1,
    postedOn: '2023-10-28',
    title: 'iOS Developer',
    company: 'TechWave Solutions',
    type: 'Full Time',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['SwiftUI', 'UiKit', 'Core Data'],
    job_link: 'https://techwave.com/careers',
  },
  {
    id: 2,
    postedOn: '2023-10-24',
    title: 'Frontend Developer',
    type: 'Full time',
    location: 'In-office',
    experience: 'Fresher',
    company: 'Webify Corp',
    skills: ['Javascript', 'Nextjs', 'Tailwind CSS'],
    job_link: 'https://webifycorp.jobs/en/',
  },
  {
    id: 3,
    postedOn: '2023-11-02',
    title: 'Android Developer',
    type: 'Part time',
    location: 'Remote',
    experience: 'Senior Level',
    company: 'InnoSoft LLC',
    skills: ['Kotlin', 'MVVM'],
    job_link: 'https://innosoft.com/careers',
  },
  {
    id: 4,
    postedOn: '2023-11-01',
    title: 'Developer Advocate',
    type: 'Contract',
    location: 'Hybrid',
    experience: 'Junior Level',
    company: 'NetStream Media',
    skills: ['web3', 'Content Creation', 'Community'],
    job_link: 'https://netstreammedia.jobs/',
  },
];
